[[main]]
  name = "InÃ­cio"
  url = ""
  weight = -110

[[main]]
  name = "Arquivos"
  url = "post/rich-content/"
  weight = -109

# Submenus are done this way: parent -> identifier
# [[main]]
#   name = "Links"
#   identifier = "Links"
#   weight = -108
# [[main]]
#   parent = "Links"
#   name = "LinkedIn"
#   url = "https://www.linkedin.com/"
# [[main]]
#   parent = "Links"
#   name = "Twitter"
#   url = "https://twitter.com/"

[[main]]
  name = "Dashboard"
  url = "https://lfpazevedo.pythonanywhere.com/"
  weight = -108
  
[[main]]
  name = "Sobre"
  url = "about/"
  weight = -107